import Head from "next/head"
import { NavBar } from "../NavBar"
import { Inter } from 'next/font/google'
import styles from '../../styles/Home.module.css'
import { ReactNode } from "react"

const inter = Inter({ subsets: ['latin'] })

interface MainLayoutProps {
  children: ReactNode
  }

export const MainLayout = ({children}:MainLayoutProps) => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        <NavBar />
        {children}
      </main>
    </>
  )
}
